### ISSUE TITLE
No metrics for expired certificates

### ISSUE THREAD

**Issue by olavst-spk** [vdbulcke/cert-monitor#23]
Hi. Thanks for making this tool! 

I ran into an issue with the Prometheus metrics and expired certificates. Here is an example config that illustrates the problem using [a sample URL from badssl.com](https://badssl.com):
```yaml
prometheus_listening_port: 9000

remote_tls_endpoints:
- address: https://expired.badssl.com/

##
# Same problem when using remote_tcp_tls_endpoints
# But in this case no errors are printed in the logs
##
#remote_tcp_tls_endpoints:
#- address: expired.badssl.com
#  port: 443
```
With this config I would expect to get metrics for the remote certificate and the `certmonitor_certificate_expiration_count` metric should be 1. 

Instead, this is printed in the logs. 
```
2025-06-24T16:43:27.716+0200 [ERROR] cert-monitor: Error Connection: address=https://expired.badssl.com/ err="Head \"https://expired.badssl.com/\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-06-24T16:43:27+02:00 is after 2015-04-12T23:59:59Z"
```
And I don't get any metrics for the remote certificate. Since I don't get any metrics `certmonitor_certificate_expiration_count` is 0.
